# Generated by Django 6.0 on 2025-12-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('endpoint', models.URLField()),
            ],
            options={
                'permissions': [('manage_ai_architecture', 'Can manage AI architecture')],
            },
        ),
    ]
