# Generated by Django 6.0 on 2026-02-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0002_esp32device_chatsession_chatmessage_devicecommand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp32device',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the device', null=True),
        ),
    ]
