# Generated by Django 6.0 on 2026-03-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0003_esp32device_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp32device',
            name='auth_token',
            field=models.CharField(blank=True, help_text='Unique token for device authentication', max_length=64, unique=True),
        ),
    ]
