# Generated by Django 6.0 on 2026-03-03 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0004_esp32device_auth_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên Server')),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='Device ID')),
                ('domain', models.CharField(blank=True, max_length=255, verbose_name='Domain')),
                ('subdomain', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Subdomain')),
                ('server_type', models.CharField(choices=[('private', 'Private Server'), ('public', 'Public Server')], default='private', max_length=20, verbose_name='Loại Server')),
                ('connection_method', models.CharField(choices=[('http', 'HTTP Direct'), ('ddns', 'Dynamic DNS'), ('vpn', 'VPN Tunnel'), ('cloudflare', 'Cloudflare Tunnel')], default='http', max_length=20, verbose_name='Phương thức kết nối')),
                ('auth_token', models.CharField(max_length=128, unique=True, verbose_name='Token xác thực')),
                ('api_key', models.CharField(blank=True, max_length=128, unique=True, verbose_name='API Key')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Vị trí')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('is_public', models.BooleanField(default=False, verbose_name='Công khai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Chủ sở hữu')),
            ],
            options={
                'verbose_name': 'MCP Server',
                'verbose_name_plural': 'MCP Servers',
                'permissions': [('manage_mcp_servers', 'Can manage MCP servers')],
            },
        ),
    ]
