# Generated by Django 6.0 on 2026-03-11 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0007_fix_subdomain_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esp32device',
            name='mqtt_topic',
        ),
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên cấu hình')),
                ('is_default', models.BooleanField(default=False, verbose_name='Mặc định')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('stt_engine', models.CharField(choices=[('google_speech', 'Google Speech Recognition'), ('whisper', 'OpenAI Whisper'), ('phowhisper', 'PhoWhisper (Vietnamese)'), ('azure_speech', 'Azure Speech')], default='google_speech', max_length=20, verbose_name='STT Engine')),
                ('stt_language', models.CharField(choices=[('vi-VN', 'Tiếng Việt'), ('en-US', 'Tiếng Anh'), ('auto', 'Tự động')], default='vi-VN', max_length=10, verbose_name='Ngôn ngữ STT')),
                ('llm_provider', models.CharField(choices=[('ollama', 'Ollama (Local)'), ('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('claude', 'Anthropic Claude')], default='ollama', max_length=20, verbose_name='LLM Provider')),
                ('llm_model', models.CharField(default='qwen2.5:1.5b', max_length=100, verbose_name='Model Name')),
                ('llm_temperature', models.FloatField(default=0.1, verbose_name='Temperature')),
                ('llm_max_tokens', models.IntegerField(default=250, verbose_name='Max Tokens')),
                ('openai_api_key', models.TextField(blank=True, null=True, verbose_name='OpenAI API Key')),
                ('gemini_api_key', models.TextField(blank=True, null=True, verbose_name='Gemini API Key')),
                ('claude_api_key', models.TextField(blank=True, null=True, verbose_name='Claude API Key')),
                ('azure_speech_key', models.TextField(blank=True, null=True, verbose_name='Azure Speech Key')),
                ('tts_engine', models.CharField(choices=[('gtts', 'Google TTS'), ('azure_tts', 'Azure TTS'), ('elevenlabs', 'ElevenLabs'), ('pyttsx3', 'Local TTS')], default='gtts', max_length=20, verbose_name='TTS Engine')),
                ('tts_voice', models.CharField(default='vi', max_length=50, verbose_name='Giọng đọc')),
                ('tts_speed', models.FloatField(default=1.0, verbose_name='Tốc độ đọc')),
                ('tts_pitch', models.FloatField(default=1.0, verbose_name='Tông giọng')),
                ('custom_stt_endpoint', models.URLField(blank=True, null=True, verbose_name='Custom STT Endpoint')),
                ('custom_stt_port', models.IntegerField(blank=True, null=True, verbose_name='Custom STT Port')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Để trống cho cấu hình mặc định, gán user cho cấu hình cá nhân', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
