# Generated by Django 6.0 on 2026-03-11 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0008_remove_esp32device_mqtt_topic_aiconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIConfig',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='azure_speech_key',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='claude_api_key',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='custom_stt_endpoint',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='gemini_api_key',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='llm_provider',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='openai_api_key',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='tts_engine',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='tts_pitch',
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='custom_stt_port',
            field=models.IntegerField(default=8000, verbose_name='Port STT Server'),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='llm_max_tokens',
            field=models.IntegerField(default=250, verbose_name='Độ dài trả lời tối đa'),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='llm_model',
            field=models.CharField(default='qwen2.5:1.5b', max_length=100, verbose_name='Model AI'),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='llm_temperature',
            field=models.FloatField(default=0.1, verbose_name='Độ sáng tạo (0-2)'),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='stt_engine',
            field=models.CharField(choices=[('google_speech', 'Google Speech Recognition'), ('custom', 'Custom STT Server (localhost)')], default='google_speech', max_length=20, verbose_name='Speech-to-Text'),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='stt_language',
            field=models.CharField(choices=[('vi-VN', 'Tiếng Việt'), ('en-US', 'Tiếng Anh')], default='vi-VN', max_length=10, verbose_name='Ngôn ngữ'),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Để trống cho cấu hình mặc định', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
