# Generated by Django 6.0 on 2026-03-11 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0009_delete_aiconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceControlLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(help_text='Tên kênh (VD: relay1, gpio2)', max_length=50)),
                ('label', models.CharField(help_text='Nhãn hiển thị (VD: Quạt, Đèn chùm)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='ai_hub.esp32device')),
            ],
            options={
                'verbose_name': 'Device Label',
                'verbose_name_plural': 'Device Labels',
                'unique_together': {('device', 'channel')},
            },
        ),
    ]
