# Generated by Django 6.0 on 2026-03-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0010_devicecontrollabel'),
    ]

    operations = [
    ]
