# Generated by Django 6.0 on 2026-03-11 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0011_debug_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='ai_hub.esp32device'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Thời gian hết hạn của session', null=True),
        ),
    ]
