# Generated by Django 6.0 on 2026-03-12 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0012_chatsession_device_chatsession_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='confidence',
        ),
    ]
