# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0013_remove_chatmessage_confidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tool ID')),
                ('display_name', models.CharField(max_length=200, verbose_name='Tên hiển thị')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('tool_type', models.CharField(choices=[('builtin', 'Built-in Tool'), ('external_api', 'External API'), ('database', 'Database Query'), ('custom_handler', 'Custom Handler')], default='builtin', max_length=20, verbose_name='Loại tool')),
                ('module_path', models.CharField(blank=True, max_length=255, verbose_name='Module path')),
                ('function_name', models.CharField(blank=True, max_length=100, verbose_name='Function name')),
                ('api_endpoint', models.URLField(blank=True, null=True, verbose_name='API Endpoint')),
                ('api_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=10, verbose_name='HTTP Method')),
                ('api_headers', models.JSONField(blank=True, default=dict, verbose_name='API Headers')),
                ('keywords', models.JSONField(default=list, help_text='List of keywords for smart routing', verbose_name='Keywords')),
                ('icon', models.CharField(default='fa-terminal', max_length=50, verbose_name='Icon class')),
                ('color_class', models.CharField(default='border-info text-info', max_length=50, verbose_name='CSS color class')),
                ('category', models.CharField(default='General', max_length=50, verbose_name='Category')),
                ('quick_command', models.CharField(blank=True, max_length=200, verbose_name='Quick command example')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Đang bật')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Hiển thị trên UI')),
                ('priority', models.IntegerField(default=0, help_text='Higher = checked first in routing', verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MCP Tool',
                'verbose_name_plural': 'MCP Tools',
                'ordering': ['-priority', 'category', 'name'],
            },
        ),
    ]
