# Generated by Django

from django.db import migrations


def populate_default_tools(apps, schema_editor):
    """Populate default MCP tools into database"""
    MCPTool = apps.get_model('ai_hub', 'MCPTool')
    
    default_tools = [
        # Knowledge & Search
        {
            'name': 'rag_search',
            'display_name': 'rag_search',
            'description': 'Tra cứu tài liệu nội bộ',
            'tool_type': 'builtin',
            'module_path': '.knowledge_tools',
            'function_name': 'mcp_rag_search',
            'keywords': ['rag', 'tài liệu', 'thông tin nội bộ', 'ctu', 'đại học', 'ct', 'là gì'],
            'icon': 'fa-book',
            'color_class': 'border-info text-info',
            'category': 'Knowledge',
            'quick_command': 'CTU là gì?',
            'priority': 0,
        },
        {
            'name': 'wiki_search',
            'display_name': 'wiki_search',
            'description': 'Tìm kiếm Wikipedia',
            'tool_type': 'builtin',
            'module_path': '.knowledge_tools',
            'function_name': 'mcp_wiki_search',
            'keywords': ['wikipedia', 'wiki', 'tìm kiếm', 'tìm'],
            'icon': 'fa-brands fa-wikipedia-w',
            'color_class': 'border-info text-info',
            'category': 'Knowledge',
            'quick_command': 'tìm kiếm Albert Einstein',
            'priority': 0,
        },
        {
            'name': 'wiki_summary',
            'display_name': 'wiki_summary',
            'description': 'Tóm tắt Wikipedia',
            'tool_type': 'builtin',
            'module_path': '.knowledge_tools',
            'function_name': 'mcp_wiki_summary',
            'keywords': ['wikipedia', 'wiki', 'tóm tắt', 'summary'],
            'icon': 'fa-brands fa-wikipedia-w',
            'color_class': 'border-info text-info',
            'category': 'Knowledge',
            'quick_command': 'tóm tắt Python lập trình',
            'priority': 0,
        },
        # Dictionary
        {
            'name': 'english_define',
            'display_name': 'english_define',
            'description': 'Từ điển tiếng Anh',
            'tool_type': 'builtin',
            'module_path': '.dictionary_tools',
            'function_name': 'mcp_english_define',
            'keywords': ['tiếng anh', 'english', 'từ', 'define', 'nghĩa là gì'],
            'icon': 'fa-language',
            'color_class': 'border-success text-success',
            'category': 'Dictionary',
            'quick_command': "từ laugh nghĩa là gì?",
            'priority': 0,
        },
        {
            'name': 'japanese_lookup',
            'display_name': 'japanese_lookup',
            'description': 'Từ điển tiếng Nhật',
            'tool_type': 'builtin',
            'module_path': '.dictionary_tools',
            'function_name': 'mcp_japanese_lookup',
            'keywords': ['tiếng nhật', 'japanese', 'kanji', 'hiragana', 'nghĩa là gì'],
            'icon': 'fa-torii-gate',
            'color_class': 'border-danger text-danger',
            'category': 'Dictionary',
            'quick_command': '勉強 nghĩa là gì?',
            'priority': 0,
        },
        # Science
        {
            'name': 'physics_calculation',
            'display_name': 'physics_calc',
            'description': 'Tính toán vật lý',
            'tool_type': 'builtin',
            'module_path': '.science_tools',
            'function_name': 'mcp_physics_calculation',
            'keywords': ['vật lý', 'physics', 'định luật ohm', 'tính'],
            'icon': 'fa-flask',
            'color_class': 'border-warning text-warning',
            'category': 'Science',
            'quick_command': 'tính V theo định luật Ohm với I=2A, R=10Ω',
            'priority': 0,
        },
        {
            'name': 'chemistry_calculation',
            'display_name': 'chemistry_calc',
            'description': 'Tính toán hóa học',
            'tool_type': 'builtin',
            'module_path': '.science_tools',
            'function_name': 'mcp_chemistry_calculation',
            'keywords': ['hóa học', 'chemistry', 'khối lượng mol', 'tính'],
            'icon': 'fa-atom',
            'color_class': 'border-warning text-warning',
            'category': 'Science',
            'quick_command': 'khối lượng mol của H2O',
            'priority': 0,
        },
        # IoT & System
        {
            'name': 'device_control',
            'display_name': 'device_control',
            'description': 'Điều khiển IoT',
            'tool_type': 'builtin',
            'module_path': '.device_tools',
            'function_name': 'mcp_device_control',
            'keywords': ['bật', 'tắt', 'mở', 'đóng', 'thiết bị', 'quạt', 'đèn'],
            'icon': 'fa-lightbulb',
            'color_class': 'border-primary text-primary',
            'category': 'IoT',
            'quick_command': 'Bật đèn lên nhé',
            'priority': 0,
        },
        {
            'name': 'list_devices',
            'display_name': 'list_devices',
            'description': 'Liệt kê thiết bị',
            'tool_type': 'builtin',
            'module_path': '.device_tools',
            'function_name': 'mcp_list_devices',
            'keywords': ['danh sách', 'thiết bị', 'liệt kê', 'device'],
            'icon': 'fa-microchip',
            'color_class': 'border-primary text-primary',
            'category': 'IoT',
            'quick_command': 'liệt kê thiết bị',
            'priority': 0,
        },
        {
            'name': 'system_info',
            'display_name': 'system_info',
            'description': 'Thông tin hệ thống',
            'tool_type': 'builtin',
            'module_path': '.system_tools',
            'function_name': 'mcp_system_info',
            'keywords': ['hệ thống', 'system', 'cpu', 'ram', 'thời gian'],
            'icon': 'fa-clock',
            'color_class': 'border-purple text-purple',
            'category': 'System',
            'quick_command': 'thời gian hệ thống',
            'priority': 0,
        },
        {
            'name': 'weather_info',
            'display_name': 'weather_info',
            'description': 'Thời tiết',
            'tool_type': 'builtin',
            'module_path': '.system_tools',
            'function_name': 'mcp_weather_info',
            'keywords': ['thời tiết', 'weather', 'nhiệt độ', 'hanoi', 'hcm'],
            'icon': 'fa-cloud-sun',
            'color_class': 'border-purple text-purple',
            'category': 'System',
            'quick_command': 'thời tiết hanoi',
            'priority': 0,
        },
        {
            'name': 'help_info',
            'display_name': 'help_info',
            'description': 'Trợ giúp',
            'tool_type': 'builtin',
            'module_path': '.system_tools',
            'function_name': 'mcp_help_info',
            'keywords': ['trợ giúp', 'help', 'hướng dẫn', 'lệnh'],
            'icon': 'fa-circle-question',
            'color_class': 'border-light text-light',
            'category': 'General',
            'quick_command': 'các lệnh có sẵn',
            'priority': 0,
        },
        {
            'name': 'tool_metadata',
            'display_name': 'tool_metadata',
            'description': 'Thông tin nguồn dữ liệu',
            'tool_type': 'builtin',
            'module_path': '.system_tools',
            'function_name': 'mcp_tool_metadata',
            'keywords': ['lấy ở đâu', 'từ đâu ra', 'nguồn', 'cách hoạt động'],
            'icon': 'fa-circle-info',
            'color_class': 'border-secondary text-secondary',
            'category': 'General',
            'quick_command': '',
            'priority': 100,  # Highest priority
        },
    ]
    
    for tool_data in default_tools:
        MCPTool.objects.get_or_create(
            name=tool_data['name'],
            defaults=tool_data
        )


def remove_default_tools(apps, schema_editor):
    """Remove default MCP tools"""
    MCPTool = apps.get_model('ai_hub', 'MCPTool')
    tool_names = [
        'rag_search', 'wiki_search', 'wiki_summary',
        'english_define', 'japanese_lookup',
        'physics_calculation', 'chemistry_calculation',
        'device_control', 'list_devices',
        'system_info', 'weather_info', 'help_info', 'tool_metadata'
    ]
    MCPTool.objects.filter(name__in=tool_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0014_mcptool'),
    ]

    operations = [
        migrations.RunPython(populate_default_tools, remove_default_tools),
    ]
