# Generated by Django

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0015_populate_mcptools'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMCPTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang kích hoạt')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='ai_hub.mcptool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User MCP Tool',
                'verbose_name_plural': 'User MCP Tools',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'tool')},
            },
        ),
    ]
