# Generated by Django

from django.db import migrations


def assign_default_tools_to_users(apps, schema_editor):
    """Assign default tools to all existing users"""
    UserMCPTool = apps.get_model('ai_hub', 'UserMCPTool')
    MCPTool = apps.get_model('ai_hub', 'MCPTool')
    # Use the actual User model from accounts app
    User = apps.get_model('accounts', 'User')
    
    # Get all default tools
    default_tools = MCPTool.objects.filter(
        name__in=[
            'rag_search', 'wiki_search', 'wiki_summary',
            'english_define', 'japanese_lookup',
            'physics_calculation', 'chemistry_calculation',
            'device_control', 'list_devices',
            'system_info', 'weather_info', 'help_info', 'tool_metadata'
        ]
    )
    
    # Get all users
    users = User.objects.all()
    
    # Create UserMCPTool for each user and each default tool
    for user in users:
        for tool in default_tools:
            UserMCPTool.objects.get_or_create(
                user=user,
                tool=tool,
                defaults={'is_active': True}
            )
    
    print(f"Assigned default tools to {users.count()} users")


def remove_user_tool_assignments(apps, schema_editor):
    """Remove all user tool assignments"""
    UserMCPTool = apps.get_model('ai_hub', 'UserMCPTool')
    UserMCPTool.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0016_usermcptool'),
    ]

    operations = [
        migrations.RunPython(assign_default_tools_to_users, remove_user_tool_assignments),
    ]
