# Generated by Django 6.0 on 2026-03-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0017_assign_default_tools_to_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcptool',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Công khai (Cho phép User tự thêm)'),
        ),
        migrations.AddField(
            model_name='mcptool',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Hệ thống (Mặc định cho mọi User)'),
        ),
    ]
