# Generated by Django 6.0 on 2026-03-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0018_mcptool_is_public_mcptool_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfiguration',
            name='response_language',
            field=models.CharField(choices=[('vi', 'Tiếng Việt'), ('en', 'Tiếng Anh'), ('ja', 'Tiếng Nhật')], default='vi', max_length=10, verbose_name='Ngôn ngữ phản hồi'),
        ),
    ]
