# Generated by Django 6.0 on 2026-03-14 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0019_aiconfiguration_response_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserver',
            name='code_template',
            field=models.TextField(blank=True, verbose_name='Code Server (FastAPI Template)'),
        ),
        migrations.AddField(
            model_name='mcpserver',
            name='is_local_managed',
            field=models.BooleanField(default=False, verbose_name='Tự quản lý code'),
        ),
        migrations.AddField(
            model_name='mcpserver',
            name='last_test_log',
            field=models.TextField(blank=True, verbose_name='Logs chạy thử'),
        ),
        migrations.AddField(
            model_name='mcptool',
            name='mcp_schema',
            field=models.JSONField(blank=True, default=dict, help_text='Full JSON schema for the tool (params, descriptions)', verbose_name='MCP Schema'),
        ),
        migrations.AddField(
            model_name='mcptool',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='ai_hub.mcpserver'),
        ),
    ]
