# Generated by Django 6.0 on 2026-03-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0020_mcpserver_code_template_mcpserver_is_local_managed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='tts_voice',
            field=models.CharField(choices=[('vi', 'Tiếng Việt'), ('en', 'Tiếng Anh (Default)'), ('en-us', 'Tiếng Anh (Mỹ)'), ('en-uk', 'Tiếng Anh (Anh)'), ('ja', 'Tiếng Nhật'), ('ko', 'Tiếng Hàn'), ('zh-cn', 'Tiếng Trung (Phổ thông)'), ('fr', 'Tiếng Pháp'), ('de', 'Tiếng Đức')], default='vi', max_length=10, verbose_name='Giọng đọc/Ngôn ngữ'),
        ),
    ]
