# Generated by Django 6.0 on 2026-03-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0021_alter_aiconfiguration_tts_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfiguration',
            name='stt_custom_url',
            field=models.CharField(blank=True, help_text='Ví dụ: http://localhost:8000/transcribe', max_length=255, null=True, verbose_name='Custom STT API URL'),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='tts_custom_url',
            field=models.CharField(blank=True, help_text='Ví dụ: http://localhost:8001/synthesize', max_length=255, null=True, verbose_name='Custom TTS API URL'),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='tts_engine',
            field=models.CharField(choices=[('gtts', 'Google TTS (Mặc định)'), ('custom', 'Custom TTS API (Cấu hình riêng)')], default='gtts', max_length=20, verbose_name='Text-to-Speech Engine'),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='custom_stt_port',
            field=models.IntegerField(default=8000, verbose_name='Port STT Server (Legacy)'),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='stt_engine',
            field=models.CharField(choices=[('google_speech', 'Google Speech Recognition (Online)'), ('vosk', 'Vosk (Offline)'), ('whisper', 'OpenAI Whisper (Local)'), ('custom', 'Custom STT API (Cấu hình riêng)')], default='google_speech', max_length=20, verbose_name='Speech-to-Text Engine'),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='stt_language',
            field=models.CharField(choices=[('vi-VN', 'Tiếng Việt'), ('en-US', 'Tiếng Anh')], default='vi-VN', max_length=10, verbose_name='Ngôn ngữ STT'),
        ),
    ]
