# Generated by Django 6.0 on 2026-03-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0022_aiconfiguration_stt_custom_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='stt_custom_url',
            field=models.CharField(blank=True, help_text='Ví dụ: http://localhost:5000/stt', max_length=255, null=True, verbose_name='Custom STT API URL'),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='stt_engine',
            field=models.CharField(choices=[('vosk', 'Vosk (Offline - Siêu nhẹ)'), ('whisper', 'OpenAI Whisper (Local - Thông minh)'), ('custom', 'Custom STT API (Tùy chỉnh)')], default='vosk', max_length=20, verbose_name='Speech-to-Text Engine'),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='stt_language',
            field=models.CharField(choices=[('vi-VN', 'Tiếng Việt'), ('en-US', 'Tiếng Anh'), ('ja-JP', 'Tiếng Nhật')], default='vi-VN', max_length=10, verbose_name='Ngôn ngữ STT'),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='tts_custom_url',
            field=models.CharField(blank=True, help_text='Ví dụ: http://localhost:5000/tts', max_length=255, null=True, verbose_name='Custom TTS API URL'),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='tts_engine',
            field=models.CharField(choices=[('local', 'System TTS (Offline - Siêu nhẹ)'), ('custom', 'Custom TTS API (Tùy chỉnh)')], default='local', max_length=20, verbose_name='Text-to-Speech Engine'),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='tts_voice',
            field=models.CharField(choices=[('vi', 'Tiếng Việt'), ('en', 'Tiếng Anh'), ('ja', 'Tiếng Nhật')], default='vi', max_length=10, verbose_name='Ngôn ngữ đọc'),
        ),
    ]
