# Generated by Django 6.0 on 2026-03-15 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0023_alter_aiconfiguration_stt_custom_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên cấu hình LLM')),
                ('model', models.CharField(choices=[('qwen2.5:0.5b', 'Qwen2.5 0.5B (Siêu nhẹ - Nhanh nhất)'), ('qwen2.5:1.5b', 'Qwen2.5 1.5B (Nhẹ - Cân bằng)'), ('qwen2.5:3b', 'Qwen2.5 3B (Thông minh)'), ('qwen2.5:7b', 'Qwen2.5 7B (Cao cấp)'), ('qwen2.5:14b', 'Qwen2.5 14B (Chuyên nghiệp)')], default='qwen2.5:1.5b', max_length=50, verbose_name='Model AI (Qwen2.5 Series)')),
                ('temperature', models.FloatField(default=0.1, help_text='0: Rất bảo thủ, 2: Rất sáng tạo', verbose_name='Độ sáng tạo (0-2)')),
                ('max_tokens', models.IntegerField(default=250, help_text='Số token tối đa trong một phản hồi', verbose_name='Độ dài trả lời tối đa')),
                ('response_language', models.CharField(choices=[('vi', 'Tiếng Việt'), ('en', 'Tiếng Anh'), ('ja', 'Tiếng Nhật'), ('ko', 'Tiếng Hàn'), ('zh', 'Tiếng Trung')], default='vi', max_length=10, verbose_name='Ngôn ngữ phản hồi')),
                ('system_prompt', models.TextField(blank=True, help_text='Hướng dẫn cho AI về cách phản hồi', verbose_name='System Prompt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Configuration',
                'verbose_name_plural': 'LLM Configurations',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='STTConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên cấu hình STT')),
                ('engine', models.CharField(choices=[('vosk', 'Vosk (Offline - Siêu nhẹ)'), ('whisper', 'OpenAI Whisper (Local - Thông minh)'), ('custom', 'Custom STT API (Tùy chỉnh)')], default='vosk', max_length=20, verbose_name='Speech-to-Text Engine')),
                ('language', models.CharField(choices=[('vi-VN', 'Tiếng Việt'), ('en-US', 'Tiếng Anh'), ('ja-JP', 'Tiếng Nhật'), ('ko-KR', 'Tiếng Hàn'), ('zh-CN', 'Tiếng Trung')], default='vi-VN', max_length=10, verbose_name='Ngôn ngữ nhận diện')),
                ('custom_url', models.CharField(blank=True, help_text='Ví dụ: http://localhost:5000/stt', max_length=255, null=True, verbose_name='Custom STT API URL')),
                ('model_size', models.CharField(choices=[('tiny', 'Tiny (Nhanh nhất)'), ('base', 'Base (Cân bằng)'), ('small', 'Small (Chính xác)'), ('medium', 'Medium (Rất chính xác)')], default='base', max_length=20, verbose_name='Kích thước model')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'STT Configuration',
                'verbose_name_plural': 'STT Configurations',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TTSConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên cấu hình TTS')),
                ('engine', models.CharField(choices=[('system', 'System TTS (Offline - Siêu nhẹ)'), ('piper', 'Piper TTS (Local - Chất lượng cao)'), ('custom', 'Custom TTS API (Tùy chỉnh)')], default='system', max_length=20, verbose_name='Text-to-Speech Engine')),
                ('language', models.CharField(choices=[('vi', 'Tiếng Việt'), ('en', 'Tiếng Anh'), ('ja', 'Tiếng Nhật'), ('ko', 'Tiếng Hàn'), ('zh', 'Tiếng Trung')], default='vi', max_length=10, verbose_name='Ngôn ngữ đọc')),
                ('custom_url', models.CharField(blank=True, help_text='Ví dụ: http://localhost:5000/tts', max_length=255, null=True, verbose_name='Custom TTS API URL')),
                ('voice_id', models.CharField(blank=True, help_text='ID của giọng đọc (để trống để dùng mặc định)', max_length=50, verbose_name='Voice ID')),
                ('speed', models.FloatField(default=1.0, help_text='0.5: Chậm, 1.0: Bình thường, 2.0: Nhanh', verbose_name='Tốc độ đọc')),
                ('pitch', models.FloatField(default=1.0, help_text='0.5: Trầm, 1.0: Bình thường, 2.0: Cao', verbose_name='Tông giọng')),
                ('volume', models.FloatField(default=1.0, help_text='0.1: Yếu, 1.0: Bình thường, 2.0: To', verbose_name='Âm lượng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TTS Configuration',
                'verbose_name_plural': 'TTS Configurations',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='custom_stt_port',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='llm_max_tokens',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='llm_model',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='llm_temperature',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='response_language',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='stt_custom_url',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='stt_engine',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='stt_language',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='tts_custom_url',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='tts_engine',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='tts_speed',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='tts_voice',
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='description',
            field=models.TextField(blank=True, help_text='Mô tả về cấu hình AI này', verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên cấu hình AI'),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='llm_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_hub.llmconfiguration', verbose_name='Cấu hình LLM'),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='stt_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_hub.sttconfiguration', verbose_name='Cấu hình STT'),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='tts_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_hub.ttsconfiguration', verbose_name='Cấu hình TTS'),
        ),
    ]
