# Generated by Django 6.0 on 2026-03-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0024_llmconfiguration_sttconfiguration_ttsconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpserver',
            name='server_type',
            field=models.CharField(choices=[('private', 'Private Server'), ('public', 'Public Server'), ('local', 'Local Server (Auto-scanned)')], default='private', max_length=20, verbose_name='Loại Server'),
        ),
    ]
