# Generated by Django 6.0 on 2026-03-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0027_hide_builtin_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfiguration',
            name='router_model',
            field=models.CharField(default='qwen2.5:0.5b', help_text='Model nhỏ/nhanh dùng cho AI Router để phân tích intent', max_length=50, verbose_name='Model Router'),
        ),
        migrations.AddField(
            model_name='llmconfiguration',
            name='router_timeout',
            field=models.IntegerField(default=3, help_text='Thời gian tối đa chờ AI Router phản hồi trước khi fallback', verbose_name='Router Timeout (giây)'),
        ),
    ]
