# Generated by Django 6.0 on 2026-03-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0031_rag_search_system_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfiguration',
            name='max_tokens',
            field=models.IntegerField(default=1024, help_text='Số token tối đa trong một phản hồi', verbose_name='Độ dài trả lời tối đa'),
        ),
        migrations.AlterField(
            model_name='sttconfiguration',
            name='engine',
            field=models.CharField(choices=[('whisper', 'Faster-Whisper (Local)'), ('custom', 'Custom STT API (Tùy chỉnh)')], default='whisper', max_length=20, verbose_name='Speech-to-Text Engine'),
        ),
        migrations.AlterField(
            model_name='ttsconfiguration',
            name='engine',
            field=models.CharField(choices=[('piper', 'Piper TTS / sherpa-onnx (Local)'), ('custom', 'Custom TTS API (Tùy chỉnh)')], default='piper', max_length=20, verbose_name='Text-to-Speech Engine'),
        ),
    ]
