# Generated by Django 6.0 on 2026-03-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0032_alter_llmconfiguration_max_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='rag_documents/%Y/%m/', verbose_name='File gốc'),
        ),
    ]
