# Generated by Django 6.0 on 2026-03-20 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0042_rich_tool_descriptions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên bộ tri thức')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('namespace', models.CharField(help_text='Namespace trong RAG service (vd: kb_history, kb_physics)', max_length=100, unique=True, verbose_name='RAG Namespace')),
                ('icon', models.CharField(default='fa-book', max_length=50, verbose_name='Icon class')),
                ('color_class', models.CharField(default='border-info text-info', max_length=50, verbose_name='CSS color class')),
                ('category', models.CharField(default='General', max_length=50, verbose_name='Danh mục')),
                ('is_public', models.BooleanField(default=True, verbose_name='Công khai (User có thể thêm)')),
                ('is_system', models.BooleanField(default=False, verbose_name='Hệ thống (Tự động áp dụng cho mọi user)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tạo bởi')),
            ],
            options={
                'verbose_name': 'Knowledge Base',
                'verbose_name_plural': 'Knowledge Bases',
                'ordering': ['-is_system', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('kb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='ai_hub.knowledgebase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Knowledge Base',
                'verbose_name_plural': 'User Knowledge Bases',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'kb')},
            },
        ),
    ]
