# Generated by Django 6.0 on 2026-01-30 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên firmware')),
                ('device_type', models.CharField(choices=[('ESP32', 'ESP32'), ('ESP8266', 'ESP8266'), ('Arduino', 'Arduino'), ('Raspberry_Pi', 'Raspberry Pi'), ('Other', 'Khác')], default='ESP32', max_length=20, verbose_name='Loại thiết bị')),
                ('version', models.CharField(max_length=50, verbose_name='Phiên bản')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('bin_file', models.FileField(upload_to='firmware/', verbose_name='File .bin')),
                ('manifest_file', models.FileField(upload_to='firmware/manifests/', verbose_name='File manifest.json')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlashingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField(verbose_name='IP người dùng')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('flashed_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False, verbose_name='Thành công')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Lỗi')),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firmware.firmwarefile', verbose_name='Firmware')),
            ],
        ),
    ]
