# Generated by Django 6.0 on 2026-02-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmwarefile',
            name='hardware_image',
            field=models.ImageField(blank=True, null=True, upload_to='firmware/images/', verbose_name='Hình ảnh mạch điện'),
        ),
    ]
