# Generated by Django 6.0 on 2026-01-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/avatar-default.png', upload_to='avatars/'),
        ),
    ]
