# Generated by Django 6.0 on 2026-01-30 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('category', models.CharField(choices=[('Technical', 'Hỗ trợ kỹ thuật'), ('Installation', 'Hỗ trợ lắp đặt'), ('Product', 'Sản phẩm'), ('Billing', 'Thanh toán'), ('Other', 'Khác')], default='Technical', max_length=20, verbose_name='Danh mục')),
                ('priority', models.CharField(choices=[('Low', 'Thấp'), ('Medium', 'Trung bình'), ('High', 'Cao'), ('Urgent', 'Khẩn cấp')], default='Medium', max_length=10, verbose_name='Mức độ ưu tiên')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('status', models.CharField(choices=[('Pending', 'Chờ xử lý'), ('In_Progress', 'Đang xử lý'), ('Resolved', 'Đã giải quyết'), ('Closed', 'Đã đóng')], default='Pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_requests', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên phụ trách')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người yêu cầu')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='support_attachments/', verbose_name='File đính kèm')),
                ('filename', models.CharField(max_length=255, verbose_name='Tên file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('support_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.supportrequest')),
            ],
        ),
        migrations.CreateModel(
            name='SupportResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung phản hồi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('support_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='support.supportrequest')),
            ],
        ),
    ]
