# Generated by Django 6.0 on 2026-01-30 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportrequest',
            options={'ordering': ['-created_at'], 'permissions': [('manage_support_request', 'Can manage support requests')]},
        ),
    ]
