# Generated by Django 6.0 on 2026-02-03 02:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_review_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('vnpay', 'VNPay'), ('cod', 'Ship COD'), ('bank_transfer', 'Chuyển khoản')], max_length=20, verbose_name='Phương thức thanh toán')),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại'), ('refunded', 'Đã hoàn tiền'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã giao dịch')),
                ('vnpay_transaction_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số giao dịch VNPay')),
                ('vnpay_bank_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ngân hàng')),
                ('vnpay_card_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Loại thẻ')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='Phản hồi từ gateway')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'ordering': ['-created_at'],
            },
        ),
    ]
